services:
  ## Jobs
  pim_user.job.csv_user_export:
    class: '%pim_connector.job.simple_job.class%'
    arguments:
      - 'csv_user_export'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      -
        - '@pim_connector.step.csv_user.export'
      - true
    tags:
      - { name: akeneo_batch.job, connector: '%pim_connector.connector_name.csv%', type: '%pim_connector.job.export_type%' }

  pim_user.job.xlsx_user_export:
    class: '%pim_connector.job.simple_job.class%'
    arguments:
      - 'xlsx_user_export'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      -
        - '@pim_connector.step.xlsx_user.export'
      - true
    tags:
      - { name: akeneo_batch.job, connector: '%pim_connector.connector_name.xlsx%', type: '%pim_connector.job.export_type%' }

  ## Steps
  pim_connector.step.csv_user.export:
    class: '%pim_connector.step.item_step.class%'
    arguments:
      - 'export'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@pim_user.reader.user.database'
      - '@pim_user.processor.normalization.user'
      - '@pim_user.writer.file.csv.user'
      - 100
      - '@akeneo_batch.job.job_stopper'

  pim_connector.step.xlsx_user.export:
    class: '%pim_connector.step.item_step.class%'
    arguments:
      - 'export'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@pim_user.reader.user.database'
      - '@pim_user.processor.normalization.user'
      - '@pim_user.writer.file.xlsx.user'
      - 100
      - '@akeneo_batch.job.job_stopper'

  ## Constraint Providers
  pim_user.job.job_parameters.constraint_collection_provider.csv_user_export:
    class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleCsvExport'
    arguments:
      -
        - 'csv_user_export'
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

  pim_user.job.job_parameters.constraint_collection_provider.xlsx_user_export:
    class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\ConstraintCollectionProvider\SimpleXlsxExport'
    arguments:
      -
        - 'xlsx_user_export'
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

  ## Default values provider
  pim_user.job.job_parameters.default_values_provider.csv_user_export:
    class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\DefaultValuesProvider\SimpleCsvExport'
    arguments:
      -
        - 'csv_user_export'
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }

  pim_user.job.job_parameters.default_values_provider.xlsx_user_export:
    class: 'Akeneo\Tool\Component\Connector\Job\JobParameters\DefaultValuesProvider\SimpleXlsxExport'
    arguments:
      -
        - 'xlsx_user_export'
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }

  ## Readers
  pim_user.reader.user.database:
    class: 'Akeneo\Tool\Component\Connector\Reader\Database\Reader'
    arguments:
      - '@pim_user.repository.user'

  ## Processors:
  pim_user.processor.normalization.user:
    class: 'Akeneo\Tool\Component\Connector\Processor\Normalization\Processor'
    arguments:
      - '@pim_user.normalizer.user.standard'
      - '@akeneo_storage_utils.doctrine.object_detacher'

  ## Writers
  pim_user.writer.file.csv.user:
    class: 'Akeneo\Tool\Component\Connector\Writer\File\Csv\Writer'
    arguments:
      - '@pim_connector.array_converter.standard_to_flat.user'
      - '@pim_connector.factory.flat_item_buffer'
      - '@pim_connector.writer.file.flat_item_buffer_flusher'

  pim_user.writer.file.xlsx.user:
    class: 'Akeneo\Tool\Component\Connector\Writer\File\Xlsx\Writer'
    arguments:
      - '@pim_connector.array_converter.standard_to_flat.user'
      - '@pim_connector.factory.flat_item_buffer'
      - '@pim_connector.writer.file.flat_item_buffer_flusher'
